### ISSUE TITLE
Build fails: `swift: error: manifest parse error(s):`

### ISSUE THREAD

**Issue by heath-clink** [andriydruk/swift-weather-app#27]
I set up the swift toolchain according to the instructions at [swift-android-toolchain](https://github.com/readdle/swift-android-toolchain).

Running macOS 13.5.2, Xcode 15.0 (also tried with Xcode 14.2, same result), Apple silicon CPU

```
$ ./gradlew assembleDebug
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Task :app:installSwiftTools
Installing Swift Build Tools v1.9.7-swift5.4
Swift Build Tools v1.9.7-swift5.4 installed

> Task :app:swiftBuildArm64Debug
Swift PM flags: --configuration debug -Xswiftc -DDEBUG
/Users/redacted-username/src/swift-weather-app/android/app/src/main/swift: error: manifest parse error(s):
error: fatalError
/Users/redacted-username/src/swift-weather-app/android/app/src/main/swift/Package.swift:3:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
unable to restore state from /Users/redacted-username/src/swift-weather-app/android/app/src/main/swift/.build/workspace-state.json; unsupported schema version 5

> Task :app:swiftBuildArm64Debug FAILED

FAILURE: Build failed with an exception.

**Comment by andriydruk** [comment]
Hi
The current version of Swift Weather works only with 5.4
That's why you need XCode 13 as it was mentioned in the [readme](https://github.com/readdle/swift-android-toolchain/tree/master)

> [IMPORTANT] Install XCode 13.0 and make it default in Command Line

I'm working on supporting Swift 5.7 it will be compatible with Xcode 14.2
